# Generated by Django 5.2.5 on 2025-08-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groceries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Groceries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='groceries_g_name_a55e08_idx'), models.Index(fields=['location'], name='groceries_g_locatio_8384e1_idx')],
            },
        ),
    ]
