# Generated by Django 5.2.5 on 2025-08-21 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groceries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_incomes', to='groceries.grocery')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Income',
                'verbose_name_plural': 'Daily Incomes',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['grocery', 'date'], name='income_dail_grocery_a57225_idx'), models.Index(fields=['date'], name='income_dail_date_5bacd3_idx')],
                'unique_together': {('grocery', 'date')},
            },
        ),
    ]
